import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

const inter = Poppins({ weight: ['100', '300', '400', '500', '700'], subsets: ['latin'] })

export const metadata: Metadata = {
	title: ' Impacta Tecnologia & Soluções em TI',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='pt-br'>
			<body className={inter.className + ' text-gray-800 bg-zinc-100'}>{children}</body>
		</html>
	)
}

